version: '3.8'

services:
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - DEBUG=false
    volumes:
      - ./.env:/app/.env:ro  # Monta o .env como somente leitura
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Versão de desenvolvimento
  api-dev:
    build: .
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - DEBUG=true
    volumes:
      - .:/app
      - ./.env:/app/.env:ro
    restart: unless-stopped
    profiles:
      - dev
